### ISSUE TITLE
Plugin failed to load : Failed to open plugin (Teamspeak 3.1)

### ISSUE THREAD

**Issue by Miscni** [mfreiholz/ts3video#49]
Fresh Windows 10 Home 64-bit install.

Plugin is installed.

But the first error we get is : Plugin Failed to load : Failed to load plugin.

Then we press Reload all in Addons. And we get a second error : Plugin failed to load : Failed to open plugin.: 808616278 (Current: 21)

Then we press Reload all in Addons again and get this here : Plugin failed to load: Failed to open plugin.: -1131656872 (current : 21)

When we press reload the third time, then it starts to randomly changes from the 2 first errors.

Problem is, that we experience alot of those issue with install, even though that we do restart the computer.

**Comment by Miscni** [comment]
Windows has forgotten some updates, trying to get it up to date, before I write more info.

**Comment by Miscni** [comment]
Windows 10 Home 64, is fully updated, and that only computer is giving that error.

**Comment by mfreiholz** [comment]
Hm.. with the latest TeamSpeak is get the same error. It looks like they changed the API again.
I will take a detailed look and release a new version *grml*

**Comment by mfreiholz** [comment]
Are there any more information in logs of TeamSpeak? :-/

**Comment by Miscni** [comment]
Logs shows, that the plugin is not there, but it is installed
`2017-02-03 22:33:54.803701|INFO    |              |   |TeamSpeak 3 Client 3.1.0.1 (2017-01-12 12:10:40)
2017-02-03 22:33:54.819327|INFO    |              |   |SystemInformation: Windows 10 (14393) x64 (AMD or Intel) Binary: 64bit
2017-02-03 22:33:54.819327|INFO    |              |   |Using hardware aes
2017-02-03 22:33:54.819327|DEBUG   |Direct Sound  |   |setting timer resolution to 1ms
2017-02-03 22:33:54.893951|INFO    |Addons        |   |Checking for addon updates...
2017-02-03 22:33:54.899956|INFO    |Plugins       |   |Loading plugin: clientquery_plugin.dll
2017-02-03 22:33:54.902958|INFO    |Query         |   |listening on 127.0.0.1:25639
2017-02-03 22:33:54.902958|INFO    |Plugins       |   |Loading plugin: teamspeak_control_plugin.dll
2017-02-03 22:33:54.956996|INFO    |SyncImpl      |   |Creating default config in local storage`

**Comment by Miscni** [comment]
Client log gives this error :
06-02-2017 15:02:34	Plugins	Info	Failed to load plugin: C:\Users\Line\AppData\Roaming\TS3Client\plugins\ts3video_win64.dll
06-02-2017 15:02:34	Plugins	Info	LoadLibrary error: 126

if you want full access to the machine, to take a look at it, then PM me on FB

**Comment by Miscni** [comment]
Okay I found out some things.

The GPU is a INTEL HD 3000

And the error is pretty basic. But the fix for it, doesn't work for Intel HD 3000

So this fix only works for AMD GPU

Here is the fix for AMD
for X64 based systems:

a. Go to the command prompt as described above. Run it as administrator.

b. Type in the following command:

C:\Windows\System32\ copy atio6axx.dll .dll

c. Restart the PC, and check again for the issue.

More info about it, can be found here : https://answers.microsoft.com/en-us/windows/forum/windows_vista-performance/error-loadlibrary-failed-with-error-126-the-module/c5b67473-00f8-4e4a-b8a5-f7f9c619c3d9

**Comment by mfreiholz** [comment]
It doesn't make any sense to have anything to do with the graphics card at the point of plugin loading (DLL loading). It must be something else.. unrelated to the used graphics card.

**Comment by Miscni** [comment]
I agreee.... also why I wrote in here... ;)

**Comment by temp23456** [comment]
Hi!

I created an account just to comment here since this is the only place with someone who had the same problem I did.

I ended up finding out that I was missing MSVCR120d.dll and all I had to do was install this:

http://www.microsoft.com/en-us/download/details.aspx?id=40784

and now it's up and running ;D

**Comment by Miscni** [comment]
Thanks for the info temp23456

But are you GPU: AMD or Nvidia?


Because as funny it may sound, I have experience with a computer right now.
Windows 7
4 GB
Nvidia Card (cant recall model number, but it is a old version)
Using Intel CPU and Nvidia Card, and it is giving errorlib 126, that is normally related to AMD.

So right now I am trying to uninstall Nvidea/RelatedtoNvidia and Framework 4.5, and after that install it again.

Trying different scenarios to figure out this problem.

**Comment by VWolf33x** [comment]
Hello! How are you? I created this account solely to be able to try to discover this error, I did not find more place on the Internet about it.

I also can not use the TS3Video plugin.

In the TS3 Addons tab, the following error appears: "Plugin failed to load: Failed to open plugin: 0 (minimum: 21, current: 22)".

My system: Win 10 64 Bits I3-3220 AMD Radeon HD 7450 8Gb Ram.
Teamspeak 3.1.1.1.

Already tried:
- Use in 32 Bit mode
- Use TS in version 3.0.6
- I re-installed and cleaned registry several times

I tried my friend Miscni's solution on atio6axx.dll, and it did not work.

I tried the temp23456 buddy solution and downloaded Visual C ++ Redistributable Packages for Visual Studio 2013 and loaded the plugin in TS. The interesting thing is that I had the versions of Visual C ++ 2008, 2010, 2012 and 2015, and none apparently worked. It was only with the installation of the 2013 version as suggested by the friend above that the plugin was loaded and recognized in TS.

BUT, the error now is this: when I go in some conference room, and I execute the command to start the call "join now", I get the following error:
"Videoclient.exe - application error. The application could not be initialized correctly (0xc000007B)".

Do you know what that can be?

**Comment by mfreiholz** [comment]
Can u try to update ur graphics driver and install the newest version of
the plugin again, please?

Sent from mobile phone.

Am 15.05.2017 17:58 schrieb "VWolf33x" <notifications@github.com>:

**Comment by VWolf33x** [comment]
Hello, mfreiholz!
Thank you for trying to help me.

I did the suggested procedure, but unfortunately I still have the same problem: "Videoclient.exe - application error. The application could not be initialized correctly (0xc000007b)".

**Comment by VWolf33x** [comment]
Hello friends!

I was able to solve the problem in the following way:

I left Teamspeak in the 64-bit version. I uninstalled everything from the computer and cleared the registry. And I did a new procedure:
I installed Teamspeak 3.1.1.1 in 32 bits.
I installed TS3Video for 32bit.
I installed Visual C ++ Redistributable Packages for Visual Studio 2013 in 32 bit.
From here the plugin was recognized, however, the videoclient.exe opened error when I tried to attend the conference. Searching for this error 0xc000007b, I found that it could be missing the following Dlls: msvcp120.dll, msvcr120d.dll and msvcr120.dll.
I downloaded these Dlls in the 32-bit version, and pasted the same folder as the videoclient.exe file.
I was able to make the program work and open the conferences.

Note: I tried to do this for 64 bits, using the same 3 Dlls in their 64 bit versions, however, the problem continued. This only worked for the 32 bit version.

The only problem is now, is that the conference opens but it gets very crashing. I have a good connection and Skype conferences happen normally, for example. However, because of the plugin the image hangs a lot, but the audio works normally. Is there any configuration to optimize, be a video problem, or something?

**Comment by mfreiholz** [comment]
Hi @VWolf33x 
Thank you for the detailed report and your effort, that is very helpful.

Can't think of the reason why you need to install *Visual C ++ Redistributable Packages for Visual Studio 2013* yourself, because the TS3VIDEO setup is doing this, too.

By the way: Even on a 64-bit system, the TS3VIDEO files are 32-bit. There is no 64-bit build on videoclient.exe. It might work when you copy the 32-bit DLLs.

Can you post information about your hardware, please?

**Comment by VWolf33x** [comment]
Hello, mfreiholz;
thank you for your support.

In the case of the C ++ package, the plugin installs the 2015 version. For some reason it does not seem to be enough. I tried installing the 2013 package as suggested by the friend above, and from there the plugin was recognized. But I really do not know why this is happening.

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i3 3220 @ 3.30GHz	
	Ivy Bridge 22nm Technology
RAM
	8,00GB Dual-Channel DDR3 @ 666MHz (9-9-9-24)
Motherboard
	ASUSTeK COMPUTER INC. P8H61-M LX3 R2.0 (LGA1155)	
Graphics
	E1941 (1366x768@60Hz)
	1024MB ATI AMD Radeon HD 7450 (XFX Pine Group)	
Storage
	223GB SanDisk SDSSDA240G ATA Device (SSD)	
	465GB Seagate ST3500312CS ATA Device (SATA)	
Optical Drives
	HL-DT-ST DVDRAM GH24NSB0 ATA Device
Audio
	VIA HD Audio(Win 10)

**Comment by VWolf33x** [comment]
Hello

So far it has been working perfectly.

But would like to know, is there any way to reduce the quality of the images, so you can run smoothly on low speed connections? I have a 2MB internet connection only, and the conferences are too slow. Perhaps by reducing quality it may be possible to have a conference without crashes.

**Comment by mfreiholz** [comment]
The quality (resolution) is defined by other clients. You would need to ask them, to use a lower resolution.

If you run your own videoserver, you can configure the maximum allowed resolution in your server's configuration file.

**Comment by Miscni** [comment]
When did that happen?
So can we go 1080p on the server now?

**Comment by mfreiholz** [comment]
Yes you can.

```ini
[default]
# Maximum allowed resolution
# e.g.: 640x480
# @version 0.6
maxresolution=1920x1080
```

The newest `default.ini` always contains all available options.

**Comment by mfreiholz** [comment]
My Validated solution for this problem:
-> **Install VC Redist 2013**

In v0.12 it will automatically come with the installer.

**Comment by eduardobd87** [comment]
Anyone know if there is the version of the ts3video plugins for linux?
